import { useState } from 'react';
import { useNavigate, useParams } from 'react-router';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, History, Info, RefreshCw } from 'lucide-react';
import { PageHeader } from '@/components/ui/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { RiskBadge } from '@/components/ui/risk-badge';
import { ContributionBars } from '@/components/prediction/contribution-bars';
import { FactorDetailModal } from '@/components/prediction/factor-detail-modal';
import { projectsApi } from '@/api/projects.api';
import { predictionsApi } from '@/api/predictions.api';
import { formatDateTime, formatShortDate, getRiskColor, getSectorLabel } from '@/utils/formatting';
import type { RiskFactor } from '@/types';
import { cn } from '@/lib/utils';

export default function PredictionDetail() {
  const navigate = useNavigate();
  const { id } = useParams();
  const projectId = id ?? '';

  const { data: project, isLoading: projectLoading } = useQuery({
    queryKey: ['project', projectId],
    queryFn: () => projectsApi.getProjectById(projectId),
    enabled: Boolean(projectId),
  });

  const { data: latest, isLoading: latestLoading } = useQuery({
    queryKey: ['prediction', 'latest', projectId],
    queryFn: () => predictionsApi.getPredictionByProjectId(projectId),
    enabled: Boolean(projectId),
  });

  const { data: explanation, isLoading: explanationLoading } = useQuery({
    queryKey: ['prediction', 'explanation', latest?.id ?? ''],
    queryFn: () => predictionsApi.getPredictionExplanation(projectId, latest?.id ?? ''),
    enabled: Boolean(latest),
  });

  const { data: history = [] } = useQuery({
    queryKey: ['prediction', 'history', projectId],
    queryFn: () => predictionsApi.getPredictionHistory(projectId),
    enabled: Boolean(projectId),
  });

  const [viewIndex, setViewIndex] = useState(0);
  const [selectedFactor, setSelectedFactor] = useState<RiskFactor | null>(null);

  const runs = latest ? [latest, ...history] : history;
  const active = runs[Math.min(viewIndex, runs.length - 1)] ?? null;

  const viewPrevious = () => setViewIndex((i) => Math.min(i + 1, runs.length - 1));

  if (projectLoading || latestLoading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-brand-primary border-t-transparent" />
      </div>
    );
  }

  if (!project || !active) {
    return (
      <div className="rounded-[var(--radius-lg)] border border-gray-200 bg-white p-10 text-center">
        <h3 className="text-base font-semibold text-gray-900">No prediction available</h3>
        <p className="mt-1.5 text-sm text-gray-500">
          Run an analysis for this project to see the explainable prediction breakdown.
        </p>
        <Button className="mt-5" onClick={() => navigate(`/prediction?project=${projectId}`)}>
          <RefreshCw className="mr-2 h-4 w-4" />
          Run New Analysis
        </Button>
      </div>
    );
  }

  return (
    <div className="animate-fade-in space-y-6">
      <button
        type="button"
        onClick={() => navigate('/prediction')}
        className="inline-flex items-center gap-1 text-xs font-medium text-gray-500 transition-colors hover:text-brand-primary"
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        AI Delay Prediction
      </button>

      <PageHeader
        title="Why is this project high risk?"
        description="Key factors contributing to the latest prediction."
      />

      {active.dataOrigin === 'demo' && (
        <div className="flex items-start gap-2.5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-900">
          <Info className="mt-0.5 h-4 w-4 shrink-0 text-amber-700" />
          <p><span className="font-bold">Demo prediction layer:</span> this explanation is generated by the existing local demo model, not a connected production ML service.</p>
        </div>
      )}

      <Card className="overflow-hidden">
        <CardContent className="flex flex-col gap-6 p-6 md:flex-row md:items-center md:justify-between">
          <div className="min-w-0">
            <p
              className="text-xs font-semibold uppercase tracking-[0.18em]"
              style={{ color: getRiskColor(active.riskLevel) }}
            >
              {viewIndex === 0 ? 'Latest Prediction' : `Previous Prediction · ${formatShortDate(active.createdAt)}`}
            </p>
            <h2 className="mt-2 truncate text-lg font-semibold text-gray-900">{active.projectName}</h2>
            <div className="mt-2 flex flex-wrap gap-2">
              <span className="rounded-md bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">{project.code}</span>
              <span className="rounded-md bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">
                {getSectorLabel(project.sector)}
              </span>
              <span className="rounded-md bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">
                {project.district}, {project.state}
              </span>
            </div>
          </div>

          <div className="flex flex-col items-start gap-4 md:items-end">
            <div className="flex items-baseline gap-2.5">
              <span
                className="text-5xl font-bold leading-none tracking-tight tabular-nums"
                style={{ color: getRiskColor(active.riskLevel) }}
              >
                {active.predictedDelay}
              </span>
              <span className="text-sm font-semibold uppercase tracking-wider text-gray-500">days delay</span>
            </div>

            <div className="flex flex-wrap items-center gap-3">
              <RiskBadge risk={active.riskLevel} />
              {active.confidence !== undefined && active.confidence !== null && (
                <span className="rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-xs font-semibold text-gray-600">
                  Confidence {active.confidence}%
                </span>
              )}
            </div>

            <div className="flex flex-wrap items-center gap-2 text-xs text-gray-400">
              <span className="font-medium text-gray-500">Model {active.modelVersion}</span>
              <span className="h-1 w-1 rounded-full bg-gray-300" />
              <span>Generated: {formatDateTime(active.createdAt)}</span>
            </div>

            <div className="flex flex-wrap items-center gap-2">
              <Button onClick={() => navigate(`/prediction?project=${project.id}`)}>
                <RefreshCw className="mr-2 h-4 w-4" />
                Run New Analysis
              </Button>
              <Button variant="outline" disabled={runs.length < 2} onClick={viewPrevious}>
                <History className="mr-2 h-4 w-4" />
                View Previous Prediction
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Key Contributing Factors</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-gray-500">Click any factor to see how it contributes to the predicted delay.</p>
            <div className="mt-4">
              <ContributionBars factors={active.factors} onSelect={setSelectedFactor} dataOrigin={active.dataOrigin} />
            </div>
          </CardContent>
        </Card>

        <Card className="h-fit">
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Model Explanation</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {viewIndex === 0 ? (
              explanationLoading ? (
                <p className="text-sm text-gray-500">Preparing model explanation…</p>
              ) : explanation ? (
                <>
                  <p className="text-sm leading-relaxed text-gray-600">{explanation.summary}</p>
                  <div className="rounded-lg border border-gray-100 bg-gray-50 p-3">
                    <p className="text-[11px] font-semibold uppercase tracking-wider text-gray-400">
                      Historical comparison
                    </p>
                    <p className="mt-1 text-xs leading-relaxed text-gray-600">{explanation.historicalComparison}</p>
                  </div>
                  <div>
                    <p className="text-[11px] font-semibold uppercase tracking-wider text-gray-400">
                      Recommended actions
                    </p>
                    <ul className="mt-2 space-y-2">
                      {explanation.recommendations.map((rec, i) => (
                        <li key={rec} className="flex items-start gap-2 text-xs leading-relaxed text-gray-700">
                          <span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-brand-accent/15 text-[9px] font-bold text-brand-primary">
                            {i + 1}
                          </span>
                          {rec}
                        </li>
                      ))}
                    </ul>
                  </div>
                </>
              ) : (
                <p className="text-sm text-gray-500">No model explanation available for this run.</p>
              )
            ) : (
              <div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2.5 text-xs leading-relaxed text-amber-700">
                This is an archived run from {formatDateTime(active.createdAt)}. Run a new analysis for the latest
                model explanation and recommended actions.
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-base">
            <History className="h-4 w-4 text-gray-400" />
            Prediction History
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="divide-y divide-gray-100 rounded-lg border border-gray-100">
            {runs.map((run, i) => {
              const isActive = i === viewIndex;
              return (
                <button
                  key={run.id}
                  type="button"
                  onClick={() => setViewIndex(i)}
                  className={cn(
                    'flex w-full items-center justify-between gap-4 px-4 py-3.5 text-left transition-colors',
                    isActive ? 'bg-[var(--color-bg-muted)]' : 'hover:bg-gray-50'
                  )}
                >
                  <div className="flex min-w-0 items-center gap-3">
                    <span
                      className={cn(
                        'h-2 w-2 shrink-0 rounded-full',
                        i === 0 ? 'bg-[var(--color-brand-accent)]' : 'bg-gray-300'
                      )}
                    />
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium text-gray-900">
                        {i === 0 ? 'Latest analysis' : formatShortDate(run.createdAt)}
                      </p>
                      <p className="text-xs text-gray-400">
                        Model {run.modelVersion} · {formatDateTime(run.createdAt)}
                      </p>
                    </div>
                  </div>
                  <div className="flex shrink-0 items-center gap-3">
                    <span className="text-sm font-semibold tabular-nums text-gray-900">{run.predictedDelay} days</span>
                    <RiskBadge risk={run.riskLevel} className="w-28 justify-center" />
                    {isActive && <span className="w-14 text-xs font-semibold text-brand-primary">Viewing</span>}
                  </div>
                </button>
              );
            })}
          </div>
        </CardContent>
      </Card>

      <FactorDetailModal factor={selectedFactor} onClose={() => setSelectedFactor(null)} />
    </div>
  );
}