/**
 * Deterministic derivation of ML feature values from current project data.
 *
 * Deliberately PURE: it takes plain data and returns plain data, performs no
 * IO, and reads no clock of its own (the snapshot moment is passed in). That
 * makes the feature definitions — the part of the system most likely to be
 * argued about and most damaging to get wrong — exhaustively testable without
 * a database.
 *
 * ###########################################################################
 * # DATA LEAKAGE BOUNDARY                                                   #
 * #                                                                        #
 * # Every value produced here MUST be observable at `asOf`. This module     #
 * # never reads, and must never be given:                                   #
 * #                                                                        #
 * #   actual_outcomes.*        delay_days_target                            #
 * #   actual_delay_days        delay_months_target                          #
 * #   predictions.*            projects.actual_completion_date              #
 * #   any realised cost overrun or post-hoc assessment                      #
 * #                                                                        #
 * # The input type below is the enforcement mechanism: it simply has no     #
 * # field for outcome data, so a caller cannot pass one in. Ground truth    #
 * # lives in actual_outcomes and is joined only at training time.           #
 * ###########################################################################
 *
 * TWO CONVENTIONS WORTH KNOWING
 *
 * 1. Derived numerics are COPIED, never recomputed. `acquisition_percentage`,
 *    `compensation_pending` and `compensation_pending_percentage` are read
 *    straight from the generated columns PostgreSQL already calculated. This
 *    avoids float error on exact-decimal values and guarantees the snapshot
 *    agrees with the row it was taken from — recomputing in JavaScript could
 *    silently drift.
 *
 * 2. Missing inputs produce NULL, never a substitute. A fabricated 0 for an
 *    unknown value is indistinguishable from a real measurement of zero, and
 *    would be learned as fact. Where the schema allows NULL, that is what an
 *    absent input yields.
 */

import { ACTIVE_STATUSES } from '../validators/common.validator';

// --- source shapes ----------------------------------------------------------
// Only the columns actually consumed are declared, so it is visible at a
// glance what feeds a snapshot.

export interface ProjectSource {
  id: string;
  planned_start_date: string | null;
}

export interface LandAcquisitionSource {
  land_required_ha: string | null;
  land_acquired_ha: string | null;
  /** Generated by PostgreSQL — copied, not recomputed. */
  land_acquisition_percentage: string | null;
  affected_landowners: number | null;
  affected_families: number | null;
  possession_obtained: boolean;
  notification_date: string | null;
  award_date: string | null;
  possession_date: string | null;
}

export interface CompensationSource {
  /** Both generated by PostgreSQL — copied, not recomputed. */
  compensation_pending: string | null;
  compensation_pending_percentage: string | null;
}

export interface LegalIssueSource {
  issue_type: string;
  court_case: boolean;
  status: string;
}

export interface RiskFactorSource {
  factor_type: string;
  status: string;
}

export interface SnapshotSource {
  project: ProjectSource;
  land: LandAcquisitionSource | null;
  compensation: CompensationSource | null;
  legalIssues: LegalIssueSource[];
  riskFactors: RiskFactorSource[];
  /** The instant the snapshot represents. Injected so results are reproducible. */
  asOf: Date;
}

/** Exactly the writable columns of `project_feature_snapshots`. */
export interface SnapshotFeatures {
  land_required_ha: string | null;
  land_acquired_ha: string | null;
  acquisition_percentage: string | null;
  compensation_pending: string | null;
  compensation_pending_percentage: string | null;
  affected_landowners: number | null;
  affected_families: number | null;
  court_cases_count: number;
  litigation_flag: boolean;
  land_dispute_flag: boolean;
  title_issue_flag: boolean;
  land_record_issue_flag: boolean;
  r_and_r_required: boolean;
  r_and_r_pending: boolean;
  row_issue: boolean;
  encroachment: boolean;
  forest_clearance_pending: boolean;
  possession_pending: boolean;
  administrative_delay: boolean;
  notification_delay_days: number | null;
  award_delay_days: number | null;
}

const isActive = (status: string): boolean => ACTIVE_STATUSES.includes(status);

/** Whole days between two calendar dates. Negative if `to` precedes `from`. */
function daysBetween(from: string, to: string): number {
  const MS_PER_DAY = 86_400_000;
  const start = Date.parse(`${from}T00:00:00Z`);
  const end = Date.parse(`${to}T00:00:00Z`);
  return Math.round((end - start) / MS_PER_DAY);
}

/** `asOf` as a YYYY-MM-DD calendar date in UTC. */
function asOfDate(asOf: Date): string {
  return asOf.toISOString().slice(0, 10);
}

export function deriveSnapshotFeatures(source: SnapshotSource): SnapshotFeatures {
  const { project, land, compensation, legalIssues, riskFactors, asOf } = source;
  const today = asOfDate(asOf);

  // --- legal features -------------------------------------------------------
  // Only ACTIVE issues count. A resolved dispute is part of the project's
  // history, not its current risk profile, and treating it as live would make
  // every project look permanently distressed once it had one bad month.
  const activeLegal = legalIssues.filter((i) => isActive(i.status));

  const court_cases_count = activeLegal.filter((i) => i.court_case).length;

  // The schema's CHECK requires these two to agree exactly:
  //   (litigation_flag AND count > 0) OR (NOT litigation_flag AND count = 0)
  // Deriving the flag FROM the count makes disagreement unrepresentable.
  const litigation_flag = court_cases_count > 0;

  const hasActiveLegalType = (type: string): boolean =>
    activeLegal.some((i) => i.issue_type === type);

  // --- risk-factor features -------------------------------------------------
  const hasActiveFactor = (code: string): boolean =>
    riskFactors.some((f) => f.factor_type === code && isActive(f.status));

  const hasAnyFactor = (code: string): boolean =>
    riskFactors.some((f) => f.factor_type === code);

  // R&R: "required" means the obligation was ever recorded (resolved or not);
  // "pending" means it is still open. Deriving `required` as a superset of
  // `pending` satisfies snapshot_rr_pending_requires_rr by construction.
  const r_and_r_pending = hasActiveFactor('R_AND_R_PENDING');
  const r_and_r_required = hasAnyFactor('R_AND_R_PENDING');

  // Possession is pending when either the operational record says so (an award
  // was passed but possession never taken) or an officer raised the factor.
  // The two sources can disagree, and either one is sufficient evidence.
  const possession_pending =
    hasActiveFactor('POSSESSION_PENDING') ||
    Boolean(land && land.award_date !== null && !land.possession_obtained);

  // --- elapsed-time features ------------------------------------------------
  // Both measure time ALREADY ELAPSED at `asOf`. They are inputs, never the
  // prediction target, and are computed only against dates in the past.
  //
  // award_delay_days — how long the award has been outstanding since the
  // statutory notification. Once the award lands the measure freezes at the
  // realised duration; before that it grows with the project's age.
  let award_delay_days: number | null = null;
  if (land?.notification_date) {
    const end = land.award_date ?? today;
    const elapsed = daysBetween(land.notification_date, end);
    // A notification dated in the future is a data-entry error, not a negative
    // duration. NULL is honest; a clamp to 0 would look like a real measurement.
    award_delay_days = elapsed >= 0 ? elapsed : null;
  }

  // notification_delay_days — how long after the planned project start the
  // statutory notification was issued.
  //
  // Left NULL whenever it cannot be measured honestly: no planned start date,
  // or a notification that predates the planned start (which happens in real
  // records when acquisition begins before the project is formally scheduled).
  // A negative value would violate the column's CHECK, and clamping to 0 would
  // assert "issued the same day", which is not what the data says.
  let notification_delay_days: number | null = null;
  if (project.planned_start_date) {
    const end = land?.notification_date ?? today;
    const elapsed = daysBetween(project.planned_start_date, end);
    notification_delay_days = elapsed >= 0 ? elapsed : null;
  }

  return {
    land_required_ha: land?.land_required_ha ?? null,
    land_acquired_ha: land?.land_acquired_ha ?? null,
    acquisition_percentage: land?.land_acquisition_percentage ?? null,

    compensation_pending: compensation?.compensation_pending ?? null,
    compensation_pending_percentage: compensation?.compensation_pending_percentage ?? null,

    affected_landowners: land?.affected_landowners ?? null,
    affected_families: land?.affected_families ?? null,

    court_cases_count,
    litigation_flag,
    land_dispute_flag: hasActiveLegalType('LAND_DISPUTE'),
    title_issue_flag: hasActiveLegalType('TITLE_DISPUTE'),
    land_record_issue_flag: hasActiveLegalType('LAND_RECORD_ISSUE'),

    r_and_r_required,
    r_and_r_pending,
    row_issue: hasActiveFactor('ROW_ISSUE'),
    encroachment: hasActiveFactor('ENCROACHMENT'),
    forest_clearance_pending: hasActiveFactor('FOREST_CLEARANCE_PENDING'),
    possession_pending,
    administrative_delay: hasActiveFactor('ADMINISTRATIVE_DELAY'),

    notification_delay_days,
    award_delay_days,
  };
}

// ---------------------------------------------------------------------------
// Input quality assessment
// ---------------------------------------------------------------------------

export type IssueSeverity = 'blocking' | 'warning';

export interface QualityIssue {
  severity: IssueSeverity;
  field: string;
  message: string;
}

export interface QualityReport {
  issues: QualityIssue[];
  /** Snapshot columns that will be NULL because the input was absent. */
  missingFeatures: string[];
  /** Which source records were present. */
  sources: {
    land_acquisition: boolean;
    compensation: boolean;
    legal_issues: number;
    risk_factors: number;
  };
  /** Fraction of the 21 feature columns carrying a non-null value, 0..1. */
  completeness: number;
}

const BLOCKING = (field: string, message: string): QualityIssue => ({
  severity: 'blocking',
  field,
  message,
});

const WARNING = (field: string, message: string): QualityIssue => ({
  severity: 'warning',
  field,
  message,
});

/**
 * Assess whether the current project data can support an honest snapshot.
 *
 * BLOCKING issues stop snapshot creation (422). They mean the result would be
 * misleading — a feature vector with no land data describes nothing.
 *
 * WARNINGS are returned alongside a successful snapshot. They record that a
 * feature is NULL because the input was absent, so a downstream consumer knows
 * the difference between "measured as zero" and "not known".
 *
 * Note what is NOT re-validated here: the database's own CHECK constraints.
 * Those are enforced on insert and cannot be bypassed. This function catches
 * the cases the database cannot express — mostly absence — and converts them
 * into an explanation rather than a constraint-violation string.
 */
export function assessSnapshotQuality(source: SnapshotSource): QualityReport {
  const { project, land, compensation, legalIssues, riskFactors, asOf } = source;
  const issues: QualityIssue[] = [];
  const today = asOfDate(asOf);

  if (!land) {
    issues.push(
      BLOCKING(
        'land_acquisition',
        'No land acquisition record exists for this project. Land data is the core of the feature vector; a snapshot without it would describe nothing. Create it via PUT /api/projects/:projectId/land-acquisition first.',
      ),
    );
  } else {
    if (land.land_required_ha === null) {
      issues.push(BLOCKING('land_required_ha', 'Land required is missing.'));
    }
    if (land.land_acquired_ha === null) {
      issues.push(BLOCKING('land_acquired_ha', 'Land acquired is missing.'));
    }

    if (
      land.land_required_ha !== null &&
      land.land_acquired_ha !== null &&
      Number(land.land_acquired_ha) > Number(land.land_required_ha)
    ) {
      issues.push(
        BLOCKING(
          'land_acquired_ha',
          'Land acquired exceeds land required. Correct the land acquisition record before taking a snapshot.',
        ),
      );
    }

    if (land.land_acquisition_percentage !== null) {
      const pct = Number(land.land_acquisition_percentage);
      if (!Number.isFinite(pct) || pct < 0 || pct > 100) {
        issues.push(
          BLOCKING('acquisition_percentage', 'Acquisition percentage is outside 0–100.'),
        );
      }
    }

    // Impossible chronology. The database already forbids out-of-order dates,
    // so this catches dates in the future, which it does not.
    for (const [field, value] of [
      ['notification_date', land.notification_date],
      ['award_date', land.award_date],
      ['possession_date', land.possession_date],
    ] as const) {
      if (value && value > today) {
        issues.push(
          BLOCKING(field, `${field} is in the future relative to the snapshot date.`),
        );
      }
    }

    if (!land.notification_date) {
      issues.push(
        WARNING(
          'notification_date',
          'No notification date recorded, so award_delay_days cannot be measured and will be null.',
        ),
      );
    }
    if (land.affected_landowners === null) {
      issues.push(WARNING('affected_landowners', 'Not recorded; the feature will be null.'));
    }
    if (land.affected_families === null) {
      issues.push(WARNING('affected_families', 'Not recorded; the feature will be null.'));
    }
  }

  if (!compensation) {
    issues.push(
      WARNING(
        'compensation',
        'No compensation record exists. Both compensation features will be null rather than zero — "not recorded" is not the same as "nothing outstanding".',
      ),
    );
  } else if (compensation.compensation_pending_percentage !== null) {
    const pct = Number(compensation.compensation_pending_percentage);
    if (!Number.isFinite(pct) || pct < 0 || pct > 100) {
      issues.push(
        BLOCKING(
          'compensation_pending_percentage',
          'Compensation pending percentage is outside 0–100.',
        ),
      );
    }
  }

  if (!project.planned_start_date) {
    issues.push(
      WARNING(
        'planned_start_date',
        'The project has no planned start date, so notification_delay_days cannot be measured and will be null.',
      ),
    );
  }

  const features = deriveSnapshotFeatures(source);
  const missingFeatures = Object.entries(features)
    .filter(([, v]) => v === null)
    .map(([k]) => k);

  const totalFeatures = Object.keys(features).length;
  const completeness = (totalFeatures - missingFeatures.length) / totalFeatures;

  return {
    issues,
    missingFeatures,
    sources: {
      land_acquisition: land !== null,
      compensation: compensation !== null,
      legal_issues: legalIssues.length,
      risk_factors: riskFactors.length,
    },
    completeness: Math.round(completeness * 10_000) / 10_000,
  };
}

export const hasBlockingIssues = (report: QualityReport): boolean =>
  report.issues.some((i) => i.severity === 'blocking');
